<?php
/**
 * @file
 * A description of what your module does.
 */
/**
 * Implements hook_permission().
 */
function analizador_biodiversidad_permission()
{
    return array(
        'access analizador' => array(
            'title' => t('Access analizador'),
            'description' => t('Access analizador on this site'),
        ),
    );
}

/**
 *  Implements hook_menu().
 */
function analizador_biodiversidad_menu()
{
    $items = array();
    $items['analizador'] = array(
        'title' => 'Analizador de Biodiversidad',
        'page callback' => 'analizador_callback',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => 'user_is_logged_in',
        'access arguments' => array('access content'),
    );
    $items['analizador/species/%'] = array(
        'title' => '',
        'page callback' => 'species_callback',
        'type' => MENU_NORMAL_ITEM,
        //'access callback' => 'user_is_logged_in',
        'access arguments' => array('access content'),
    );
    $items['analizador/genus/%'] = array(
        'title' => '',
        'page callback' => 'species_callback',
        'type' => MENU_NORMAL_ITEM,
        //'access callback' => 'user_is_logged_in',
        'access arguments' => array('access content'),
    );
    $items['analizador/family/%'] = array(
        'title' => '',
        'page callback' => 'species_callback',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => 'user_is_logged_in',
        'access arguments' => array('access content'),
    );
    $items['analizador/order/%'] = array(
        'title' => '',
        'page callback' => 'species_callback',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => 'user_is_logged_in',
        'access arguments' => array('access content'),
    );
    $items['analizador/institutions/%'] = array(
        'title' => '',
        'page callback' => 'species_callback',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => 'user_is_logged_in',
        'access arguments' => array('access content'),
    );
    $items['admin/settings/analizador_biodiversidad'] = array(
        'title' => 'Analizador',
        'description' => 'Settings Analizador Biodiversidad',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('analizador_biodiversidad_admin'),
        'access callback' => 'user_is_logged_in',
        'access arguments' => array('administer analizador_biodiversidad settings'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function species_callback()
{
    $path = drupal_get_path('module', 'analizador_biodiversidad');
    $content['overlay'] = array(
        '#attached' => array(
            'css' => array(
                $path . '/include/busqueda_especies.css',
            ),
            'library' => array(
                array('system', 'ui.autocomplete'),
                array('system', 'ui.slider'),
                array('system', 'ui.tabs'),
            ),
        ),
    );
    $content['overlay']['#attached']['js'] = array(
        'http://openlayers.org/en/v3.0.0/build/ol.js' => array(
            'type' => 'external',
        ),
        'http://code.highcharts.com/highcharts.js' => array(
            'type' => 'external',
        ),
        'http://l2.io/ip.js?var=myip' => array(
            'type' => 'external',
        ),
        $path.'/export-csv-master/exporting.src.js'=>array(
            'type' => 'file',
        ),
        $path.'/export-csv-master/export-csv.js'=>array(
            'type' => 'file',
        ),
        $path.'/annotations/annotations.js'=>array(
            'type' => 'file',
        ),
    );
    return $content;
}

function analizador_callback()
{
    $path = drupal_get_path('module', 'analizador_biodiversidad');
    $content['overlay'] = array(
        '#attached' => array(
            'css' => array(
                $path . '/include/analizador.css',
                $path . '/include/generalSearch.css',
            ),
            'library' => array(
                array('system', 'ui.autocomplete'),
                array('system', 'ui.slider'),
                array('system', 'ui.tabs'),
            ),
        ),
    );

    $content['overlay']['#attached']['js'] = array(
        'http://openlayers.org/en/v3.0.0/build/ol.js' => array(
            'type' => 'external',
        ),
        $path . '/highcharts/js/highcharts.js' => array(
            'type' => 'file',
        ),
    );
    return $content;
}

/**
 * Implements hook_admin().
 */
function analizador_biodiversidad_admin()
{
    $form = array();
    $var1 = variable_get('desc_chart_1');
    $var2 = variable_get('desc_chart_2');
    $var3 = variable_get('desc_chart_3');
    $form['desc_chart_1'] = array(
        '#type' => 'text_format',
        '#title' => t('Descripción de los gráficos temporales por año.'),
        '#default_value' => $var1['value'],
        '#description' => t("Gráficos de observaciones por año"),
        '#format' => $var1['format'],
    );
    $form['desc_chart_2'] = array(
        '#type' => 'text_format',
        '#title' => t('Descripción del gráfico de acumulación de especies por mes.'),
        '#default_value' => $var2['value'],
        '#description' => t("Gráfico con la acumulación de observaciones por mes."),
        '#format' => 'full_html',
    );
    $form['desc_chart_3'] = array(
        '#type' => 'text_format',
        '#title' => t('Descripción del tercer gráfico.'),
        '#default_value' => $var3['value'],
        '#description' => t("Descripción del tercer gráfico."),
        '#format' => 'full_html',
    );

    return system_settings_form($form);
}

/**
 *  Implements hook_block_list_alter().
 */
function analizador_biodiversidad_block_list_alter(&$blocks)
{
    if (current_path() === 'analizador'
        || drupal_match_path(current_path(), "analizador/species/*")
        || drupal_match_path(current_path(), "analizador/genus/*")
        || drupal_match_path(current_path(), "analizador/family/*")
        || drupal_match_path(current_path(), "analizador/order/*")
        || drupal_match_path(current_path(), "analizador/institutions/*")
    ) {
        foreach ($blocks as $i => $block) {
            if ('sidebar_first' === $block->region || 'advertise' === $block->region) {
                unset($blocks[$i]);
            }
        }
    } else {
        return;
    }
}

function analizador_biodiversidad_theme()
{
    return array(
        'analizador_page' => array(
            'template' => 'theme/analizador_page',
            'render element' => 'page'
        ),
        'species_page' => array(
            'template' => 'theme/species_page',
            'render element' => 'page',
        ),
        'genus_page' => array(
            'template' => 'theme/genus_page',
            'render element' => 'page',
        ),
        'family_page' => array(
            'template' => 'theme/family_page',
            'render element' => 'page',
        ),
        'order_page' => array(
            'template' => 'theme/order_page',
            'render element' => 'page',
        ),
        'institutions_page' => array(
            'template' => 'theme/institutions_page',
            'render element' => 'page',
        ),
    );
}

function analizador_biodiversidad_preprocess_page(&$variables, $hook)
{
    if (current_path() === 'analizador') {
        $variables['theme_hook_suggestions'][] = 'analizador_page';
    }
    if (drupal_match_path(current_path(), "analizador/species/*")) {
        $variables['theme_hook_suggestions'][] = 'species_page';
    }
    if (drupal_match_path(current_path(), "analizador/genus/*")) {
        $variables['theme_hook_suggestions'][] = 'genus_page';
    }
    if (drupal_match_path(current_path(), "analizador/family/*")) {
        $variables['theme_hook_suggestions'][] = 'family_page';
    }
    if (drupal_match_path(current_path(), "analizador/order/*")) {
        $variables['theme_hook_suggestions'][] = 'order_page';
    }
    if (drupal_match_path(current_path(), "analizador/institutions/*")) {
        $variables['theme_hook_suggestions'][] = 'institutions_page';
    }else {
        return;
    }
}